.github/workflows/python-package.yml, metadata.yaml, src/charm.py, src/mongo.py, tests/test_charm.py
- Added two test cases
- Added stop event handler
- Added doc strings to charm class
- Ensured replica set reconfiguration failure is not ignored
=> Added minimal tests, doc strings and few tweaks

src/charm.py
=> Fix missing import

charmcraft.yaml, lib/charms/mongodb_k8s/v0/mongodb.py, metadata.yaml
This PR does 2 things
- Creates a charm library in preparation for an edge release
- Updates the configuration for recent Charmcraft version
=> Create library and update charmcraft config

README.md
Current readme text can lead to legal issues.
Added legal team crafted words to avoid being sued.
=> text to avoid legal issues

README.md
this is literally just copying over already reviewed text and adding the word "Kubernetes" to it
=> copy recs, config options, and overview

.github/workflows/ci.yaml, .github/workflows/integration.yaml, .github/workflows/lint.yaml, .github/workflows/unit.yaml
* **Please check if the PR fulfills these requirements**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature
* **What is the current behavior?** (You can also link to an open issue here)
The Github Actions CI was not reusable and was monolithic.  Individual tests cannot be ran easily through Github Actions
* **What is the new behavior (if this is a feature change)?**
This PR moves the test groups into their own reusable components and allows each group to be called manually from CI.
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No.
* **Other information**:
None.
=> Break up CI implementation and add workflow_dispatch

CONTRIBUTING.md, README.md, metadata.yaml, tests/integration/ha_tests/helpers.py, tests/integration/helpers.py, tests/integration/tls_tests/helpers.py, tests/integration/tls_tests/test_tls.py
* **Please check if the PR fulfills these requirements**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature
* **What is the current behavior?** (You can also link to an open issue here)
The charm pulls the upstream image from `mongo`.
* **What is the new behavior (if this is a feature change)?**
The charm pulls the new ROCK from `dataplatformoci`
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No.
* **Other information**:
[MongoDB ROCK Docker Hub](https://hub.docker.com/r/dataplatformoci/mongodb)
=> Change OCI image to new ROCK

actions.yaml, lib/charms/mongodb/v0/mongodb.py, lib/charms/tls_certificates_interface/v1/tls_certificates.py, src/charm.py, tests/integration/ha_tests/helpers.py, tests/integration/helpers.py, tests/integration/test_charm.py, tests/integration/tls_tests/test_tls.py
Conversation with Guillermo and Mykola illustrated that a the MongoDB exporter charm couldn't run commands due to authorisation issues 
1. Create a monitor user
2. Create monitor roles
=> Add monitor user

lib/charms/mongodb/v0/helpers.py, lib/charms/mongodb/v0/mongodb_tls.py, metadata.yaml, src/charm.py, tests/integration/tls_tests/helpers.py, tests/integration/tls_tests/test_tls.py, tests/unit/test_charm.py
Update paths in k8s-charm to be of the same format as the paths in the VM-Charm but without the snap prefix dir - also update rock tag
=> Update file paths and rock tag

.github/workflows/release.yaml
Update the channel to `5/edge` pending on [the channel request](https://discourse.charmhub.io/t/request-create-5-edge-channel-for-mongodb-k8s/9082) to be completed
=> release to 5/egde

.github/workflows/ci.yaml, charmcraft.yaml, config.yaml, metadata.yaml, pyproject.toml, src/charm.py, src/licenses/LICENSE-charm, tests/integration/conftest.py, tests/integration/ha_tests/application_charm/actions.yaml, tests/integration/ha_tests/application_charm/charmcraft.yaml, tests/integration/ha_tests/application_charm/metadata.yaml, tests/integration/ha_tests/application_charm/src/charm.py, tests/integration/ha_tests/application_charm/src/continuous_writes.py, tests/integration/ha_tests/conftest.py, tests/integration/ha_tests/helpers.py, tests/integration/ha_tests/test_ha.py, tests/integration/test_charm.py, tests/integration/tls_tests/helpers.py, tests/integration/tls_tests/test_tls.py, tests/unit/__init__.py, tests/unit/test_charm.py, tests/unit/test_mongodb_provider.py, tox.ini
1. Add docs to charm
2. update copyrights
3. set ram usage
4. add rock license
=> Housekeeping

src/charm.py
fixes https://github.com/canonical/mongodb-k8s-operator/issues/106
=> Fix data directory permissions

tests/unit/test_charm.py
The goal of this PR is to add a unit tests for _connect_mongodb_exporter
to validate integration with COS
Closes: DPE-1896
=> [DPE-1896] Add unit tests for COS integration function _connect_mongodb_exporter

src/charm.py
The goal of this PR is to refactor check that the database was initialised
DPE-2143, DPE-2071
=> [DPE-2143] Refactoring check that db was initialised

lib/charms/mongodb/v0/mongodb.py, lib/charms/mongodb/v0/users.py, src/charm.py, src/exceptions.py, tests/unit/test_charm.py
The goal of this PR is to refactor users related code in K8s charm.
DPE-2144, DPE-2071
=> [DPE-2144] Refactoring: refactor user related code

src/charm.py, src/config.py, tests/integration/helpers.py
This PR is a part of an effort of converging code of MongoDB VM charm and MongoDB K8s charm .
The goal of this PR is  to extract configuration for charm into a separate file.
DPE-2146, DPE-2071
=> [DPE-2146] Refactoring: extract charm configuration

src/charm.py
The goal of this PR is to resolve issues after refactoring
DPE-2145
=> [DPE-2145] Fixes for refactoring

Makefile, lib/charms/mongodb/v0/helpers.py, lib/charms/mongodb/v0/mongodb.py, lib/charms/mongodb/v0/mongodb_provider.py, src/charm.py
All libs taken from MongoDB VM charm as is
=> [DPE-2074] sync libs from MongoDB VM charm

lib/charms/mongodb/v0/mongodb_tls.py, src/charm.py
As discussed earlier: https://github.com/canonical/mongodb-k8s-operator/pull/162#discussion_r1270525053
=> [DPE-2281] Deleting certs before pushing new ones

lib/charms/mongodb/v0/mongodb_backups.py
- Added error logs for failed events and info logs for successful events. Events are backup\restore\list backups
- Make a call order of event.defer() and logger.info() consistent
[DPE-1917](https://warthogs.atlassian.net/browse/DPE-1917)
[DPE-1917]: https://warthogs.atlassian.net/browse/DPE-1917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DPE-1917] Updated logs for backup status

.github/workflows/ci.yaml, lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/mongodb/v0/mongodb_provider.py, src/charm.py
Update library code, and make necessary change in `src/charm.py`
pin charmcraft in build due to [issue in charmcraft](https://github.com/canonical/charmcraft/issues/1179)
=> [DPE-2528] Update libraries on K8s charm so charm uses data_interfaces for provider code 

.github/workflows/ci.yaml, .github/workflows/release_5_edge.yaml, src/charm.py, tests/unit/test_charm.py
The goal of this PR is to fix the branch that will trigger publishing to 5/edge channel
=> Fix branch used to trigger release to 5/edge

lib/charms/mongodb/v0/mongodb_backups.py, src/charm.py, tests/unit/test_charm.py, tests/unit/test_mongodb_backups.py
Backup status logs error message, when not related to S3. Instead this should be info
Reported as a bug in #212 
Copy changes made from VM [see Merged pr](https://github.com/canonical/mongodb-operator/pull/305)
=> fix logging (6/edge) - via copying solution over from VM charm
