src/charm.py
There's no need to check if the pod spec has changed before running set_spec, as Juju will only apply it if things have changed.
=> No need to check if pod spec has changed before running set_spec

src/charm.py, tests/test_charm.py
This commit fixes an error introduced by a recent refactor
that does not specify the right object on which to access
the standalone_uri property.
=> Fix typo - accessing standalone uri

lib/charms/mongodb_k8s/v0/mongodb.py, requirements.txt, src/charm.py, src/mongoprovider.py, src/pebble_layers.py
This PR essentially **minimally** updates the long neglected MonoDB charm to bring it back into sync with upstream Canonical Operator Framework. These changes are
1. Point `requirements.txt` to upstream `ops` repository
2. Remove dependence on `ops.relation`
3. Remove dependence on out of spec behaviour in `ops` that has now been fixed
=> Update to sync with latest Operator Framework

lib/charms/mongodb_k8s/v0/mongodb.py
This commit updates the library patch level since dependence
on ops.relation has now been removed.
=> Updated library patch level

src/charm.py, src/mongoserver.py
This commit ensures that MongoDB server is shutdown properly
before any call to start/restart it. This avoids the PebbleChangeError
exception that is raised when the Pebble attempts to SIGKILL MongoDB
and it still fails to shutdown.
=> Shutdown Mongo sever properly

tests/test_mongoserver.py
As @marceloneppel noticed:
" The statement overwrites the host in each iteration of the for loop. It can be fixed with:
```
hosts[i] = "host{}".format(i)
```
"
=> Remove quotes from index in forloop

src/charm.py, src/mongoprovider.py, tests/test_charm.py, tests/test_mongoprovider.py
Currently, the MongoDB charm does not set any relation data into the related charms if they were related before the charm finished starting. A workaround for this was to recreate the relations after the MongoDB charm became active.
This PR addresses the issue, and adds a unit test that verifies this aspect, and it has been updated to verify that the relation data is indeed set into existing relations after MongoDB starts.
Also fixes the ``test_mongoprovider.py`` tests. A previous change [1] removed the dependency on ``ops.relation``, but the unit tests were not updated, which resulted in them failing.
[1] https://github.com/canonical/mongodb-k8s-operator/pull/17
=> Sets the db relation data on start

src/mongoprovider.py, tests/test_charm.py
If a relation was created before the MongoDB finished initializing, its relation data is finally set after it finishes initializing.
But a database join event could be triggered afterwards, or when adding a new unit, causing the charm to fail.
``consumers`` is a dictionary in which we're storing credentials based on the Relation ID, and we're storing it as a json dump,
and we're looking into to it whenever we're trying to determine if we have a new consumer.
However, ``json.dumps`` converts integers into strings, which means that we can't rely on Relation IDs being integers.
For example:
```
(Pdb) json.dumps(consumers)
'{"1": {"username": "user-1", "password": "redacted"}}'
(Pdb) consumers
{1: {'username': 'user-1', 'password': 'redacted'}}
```
This converts the Relation IDs used in …
=> Ensure unique user and credentials creation

src/mongoserver.py
This commit removes the setting of ServerSelectionTimeoutMS from
the MongoClient constructor arguments. This is because in
PyMongo 4 the default value is 30 that is longer than what it
is begin currently set too.
=> Remove server selection timeout option

requirements.txt, src/charm.py, src/mongoserver.py
The manner in which replica sets are initialized in PyMongo 4 and MongoDB 5 seems to have been changed. This PR implements a workaround to temporarily resolve this issue.
=> Workarounds for breaking changes in PyMongo and MongoDB

.github/workflows/python-package.yml, metadata.yaml, src/charm.py, src/pebble_layers.py
The MongoDB charm was initaly built as a pod spec charm. The
mongod daemon expects its key file to be present before it is
started. Hence the pod spec charm used a Kubernetes init container
and a persistent storage to create and populate the key file.
This is no longer necessary for a side car charm, since key files
can be pushed to the workload container before starting the
workload. This is exactly the workflow implemented by this
Closes: #16
=> Moved key file from persistent to container storage

requirements.txt, src/charm.py, src/mongoserver.py
This commit migrates to MongoDB charm to PyMongo version 4.
Since version 4 PyMongo is more strict in
- Requiring authentication for secured MongoDB deployments.
- Requiring initialization of replica set by connecting to a
specific host.
=> Migration to PyMongo version 4

src/mongoserver.py
The MongoDB charm checks the status of MongoDB prior to
attempting replica set initialization. This check uses
a try and fail approach. The failure is detected through
exceptions rasied which are trapped. Previous version of
PyMongo raised ServerSelectionTimeout exception. The
current version raises OperationFailure exception. This
commit updates the code to trap the new exception.
Closes: #36
=> Trap additional exception when checking ready status

.github/workflows/ci.yaml, charmcraft.yaml, tox.ini
* Poetry is not installed by tox and calls to it rely on it being installed and working system wide.
* Add poetry as a dependency to tox.
* Remove CI installation of poetry
* No additional testing should be necessary beyond existing tests working as intended.
=> Install poetry as a tox dependency

README.md
Copied over deployment guide from MongoDB-K8s ; and then added `-k8s` to the application name.
This deployment guide has already been reviewed and doesn't need a re-review.
=> Copying over deployment guide from MongoDB-k8s

.github/workflows/ci.yaml, tests/integration/ha_tests/conftest.py, tests/integration/ha_tests/helpers.py, tests/integration/ha_tests/manifests/chaos_network_loss.yml, tests/integration/ha_tests/scripts/deploy_chaos_mesh.sh, tests/integration/ha_tests/scripts/destroy_chaos_mesh.sh, tests/integration/ha_tests/test_ha.py, tests/integration/tls_tests/test_tls.py, tox.ini
* Porting more of the HA VM tests to the K8S charm
* Ported network cut and unique cluster DBs tests and necessary utility functions
* Most of the network cut test is based on similar work in the MySQL charm
* Tweaked how `deploy_and_scale_mongodb()` and `get_application_name()`, so to reuse them when deploying the second cluster and not to affect other tests in case the second cluster is already present
* Added a “cheat” pytest  cli parameter, so that `test_unique_cluster_dbs()` so that we don't necessarily need to repack the charm during `test_unique_cluster_dbs()` when testing locally against existing clusters
* network cut test
* unique cluster DBs test
=> Adding network cut and unique cluster DBs tests

.github/workflows/ci.yaml, .github/workflows/release.yaml
It is a PR to add our default release pipeline to publish the charm on https://charmhub.io/mongodb-k8s
=> Add CI/CD pipeline to publish on charmhub.io

src/charm.py, tests/unit/test_charm.py
The data directory is not always writable for the "mongodb" user (e.g. on GKE).
Unfortunately, right now, juju/operator-framework doesn't allow set fsGroup and fsGroupChangePolicy via Pod securityContext.
So it is necessary to change data directory ownership via the "chown" cmd.
=> Fix data directory permissions with chown

src/charm.py
I was reading the code and just noticed there's a typo in a comment. This fixes it and reassures devs that it is good to use comments - people do read them.
tl;dr s/eporter/exporter/
=> fix(typo): Rename eporter to exporter

tests/integration/cleanup_resources.py, tests/integration/ha_tests/helpers.py, tests/integration/ha_tests/scripts/destroy_chaos_mesh.sh, tests/integration/ha_tests/test_ha.py, tox.ini
* Fix the HA tests by replacing  a command to get MongoDB start arguments.
"ps -o cmd fp" command id replaced to  "cat /proc/{pid}/cmdline" because the
former one was truncating long output string.
* Update bash script to cleanup chaos mesh used in HA testing
* Add scripts for cleanup resources.
=> [DPE-2048] Stabilize HA tests

lib/charms/mongodb/v0/mongodb.py, lib/charms/mongodb/v0/mongodb_tls.py, metadata.yaml, src/charm.py, src/config.py, tests/integration/ha_tests/helpers.py, tests/integration/test_teardown.py, tests/unit/test_charm.py, tests/unit/test_mongodb_provider.py
This PR is a part of our efforts con converge code between MongoDB VM charm and MongoDB K8s charm
This PR introduces refactoring of charm events handlers to make them similar to MongoDB VM charm.
[DPE-2145]
[DPE-2145]: https://warthogs.atlassian.net/browse/DPE-2145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DPE-2145] Refactoring: refactor charm events handlers

.github/workflows/ci.yaml, poetry.lock, pyproject.toml, requirements.txt, tox.ini
Python libjuju cannot be installed with the latest version of PyYAML (6.0.1), which fixes a https://github.com/yaml/pyyaml/issues/601 and https://github.com/juju/python-libjuju/issues/913 caused by an update to CPython.
=> [DPE-2140] update libjuju to resolve PyYAML issue

actions.yaml, lib/charms/data_platform_libs/v0/s3.py, lib/charms/mongodb/v0/helpers.py, lib/charms/mongodb/v0/mongodb_backups.py, lib/charms/operator_libs_linux/v1/snap.py, metadata.yaml, src/charm.py, src/config.py, tests/integration/backup_tests/__init__.py, tests/integration/backup_tests/helpers.py, tests/integration/backup_tests/test_backups.py, tests/unit/test_charm.py, tests/unit/test_mongodb_backups.py, tox.ini
The goal of this PR is to
-  add backup library to MongoDB K8S charm 
- configure PBM
- Add unit and integration tests for PBM configuration
[DPE-1720], [DPE-1957]
[DPE-1720]: https://warthogs.atlassian.net/browse/DPE-1720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-1957]: https://warthogs.atlassian.net/browse/DPE-1957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DPE-1720] Add backups to k8s charm and configure PBM

src/charm.py, tests/integration/metrics_tests/test_metrics.py, tests/unit/test_charm.py
Sometimes secret id is represented in different ways https://bugs.launchpad.net/juju/+bug/2028402.
this PR workaround the juju issue.
=> [DPE-2320] fix monitor secret id parsing issue

lib/charms/mongodb/v0/helpers.py, lib/charms/mongodb/v0/mongodb_backups.py, tests/integration/backup_tests/test_backups.py, tests/unit/test_mongodb_backups.py
This PR is a follow up for [this one ](https://github.com/canonical/mongodb-k8s-operator/pull/188)where we are improving logs for backup.
In this PR we making logs consistent for successful actions
[DPE-1918](https://warthogs.atlassian.net/browse/DPE-1918)
[DPE-1918]: https://warthogs.atlassian.net/browse/DPE-1918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DPE-1918] Improve logs for backup

tests/integration/ha_tests/application_charm/src/continuous_writes.py, tests/integration/ha_tests/helpers.py, tests/integration/ha_tests/manifests/extend_pebble_restart_delay.yml, tests/integration/ha_tests/manifests/restore_pebble_restart_delay.yml, tests/integration/ha_tests/test_ha.py, tox.ini
Current HA test suite doesnt have a full cluster crash test
Add full cluster crash test
Code from the Postgres repo that changes the pebble layer was ported over (i.e. all the changes in `helpers`)
to get this test to function properly, some modifications were needed in continuous writes. Specifically we must try again when the HMAC is out of sync between the client and the cluster. The reasoning for this was discussed in Mattermost but is pasted below:
I'm running into the issue that @dragop ran into when he first attempted to do [full cluster crash test](https://github.com/canonical/mongodb-k8s-operator/pull/80) which is:
> Cluster crash/restart currently fail the assertion for total writes, meaning that the DB didn't persist some of the writes `continuous_writes.py` thinks it should …
=> [DPE-2412]  Full cluster crash test

lib/charms/mongodb/v0/helpers.py, lib/charms/mongodb/v0/mongodb_backups.py, src/charm.py, tests/unit/test_charm.py, tests/unit/test_mongodb_backups.py
Lib code has changed on K8s side, and now needs to be adapted on the VM side. Before updating on the VM side, there are some changes in the code that will not function with the VM charm:
1. `get_backup_service`, on the VM side it is not possible to return the service as it is on the K8s side. The code in this library, only uses this as a sanity check to verify that there is a backup service running, instead we change this to `has_backup_service`
2. `set_pbm_config_file `, function name is called set, but all the function does is set the pbm file to be empty, effectively clearing the file. Rename this and add a comment to elucidate why this is needed.
3. `run_pbm_restore_command` is functional for both K8s and VM so remove that from the charm code so it can be used by both charms
Update …
=> [DPE-2415] generalise lib code so easily repurposable by VM

metadata.yaml, pyproject.toml
After publishing a new charm with MongoDB 6 we need to support different docs sets for different version of charms.
Update link to documentation set in metadata.yaml
=> Update link to the documentation for MongoDB 5 charm

metadata.yaml, pyproject.toml
After publishing a new charm with MongoDB 6 we need to support different docs sets for different version of charms.
Update link to documentation set in metadata.yaml
=> Update link to documentation for MongoDB 6 charm

lib/charms/mongodb/v0/mongodb_backups.py, tests/unit/test_mongodb_backups.py
Backup status logs error message, when not related to S3. Instead this should be info
Reported as a bug in #212 
Copy changes made from VM [see Merged pr](https://github.com/canonical/mongodb-operator/pull/306)
=> fix logging (5/edge) - via copying solution over from VM charm 

lib/charms/mongodb/v0/helpers.py, metadata.yaml, src/charm.py, src/config.py, tests/unit/test_charm.py
The goal of this PR is to enable audit logging for Charmed MongoDB K8s and add audit logs to CoS
=> [DPE-2910] Enable audit logging
